<?php

namespace AppBundle\Repository;

/**
 * AvanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvanceRepository extends \Doctrine\ORM\EntityRepository
{
}
