<?php

namespace AppBundle\Repository;

/**
 * VetementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VetementsRepository extends \Doctrine\ORM\EntityRepository
{
}
